erDiagram

    agent_extensions {
        organization_id string PK
        organization_id string FK
        account_group string
        category_name string
        created_at string
        updated_at string
    }

    contacts {
        id string PK
        customer_id string FK
        created_by string FK
        updated_by string FK
        first_name string
        last_name string
        full_name string
        email string
        phone string
        mobile string
        position string
        department string
        is_primary string
        is_decision_maker string
        ...
    }

    customer_channels {
        id string PK
        code string
        name string
        created_at string
        updated_at string
        description string
        display_order string
        is_active string
    }

    customer_documents {
        id string PK
        customer_id string FK
        verified_by string FK
        created_by string FK
        updated_by string FK
        order_id string FK
        service_record_id string FK
        customer_name string
        document_type string
        document_name string
        document_number string
        issuing_country string
        issuing_authority string
        issue_date string
        expiry_date string
        is_valid string
        file_url string
        ...
    }

    customer_sources {
        id string PK
        code string
        name string
        created_at string
        updated_at string
        description string
        display_order string
        is_active string
    }

    customers {
        id string PK
        parent_customer_id string FK
        source_id string FK
        channel_id string FK
        owner_user_id string FK
        agent_user_id string FK
        agent_id string FK
        id_external string
        owner_id_external string
        owner_name string
        created_by_external string
        created_by_name string
        updated_by_external string
        updated_by_name string
        created_at_src string
        updated_at_src string
        last_action_at_src string
        ...
    }

    deliverables {
        id string PK
        order_id string FK
        order_stage_id string FK
        verified_by string FK
        uploaded_by string FK
        deliverable_type string
        name string
        description string
        file_path string
        file_url string
        file_size string
        mime_type string
        is_verified string
        verified_at string
        created_at string
        ...
    }

    menu_permissions {
        menu_id string FK
        permission_id string FK
        created_at string
    }

    menus {
        id string PK
        parent_id string FK
        code string
        name_zh string
        name_id string
        description_zh string
        description_id string
        path string
        component string
        icon string
        display_order string
        is_active string
        ...
    }

    order_assignments {
        id string PK
        order_id string FK
        assigned_to_user_id string FK
        assigned_by_user_id string FK
        vendor_id string FK
        organization_employee_id string FK
        vendor_employee_id string FK
        assignment_type string
        is_primary string
        assigned_at string
        unassigned_at string
        notes string
        created_at string
    }

    order_comments {
        id string PK
        order_id string FK
        order_stage_id string FK
        replied_to_comment_id string FK
        created_by string FK
        comment_type string
        content_zh string
        content_id string
        is_internal string
        is_pinned string
        created_at string
        updated_at string
    }

    order_files {
        id string PK
        order_id string FK
        order_item_id string FK
        order_stage_id string FK
        verified_by string FK
        uploaded_by string FK
        file_category string
        file_name_zh string
        file_name_id string
        file_type string
        file_path string
        file_url string
        file_size string
        mime_type string
        description_zh string
        description_id string
        ...
    }

    order_items {
        id string PK
        order_id string FK
        product_id string FK
        service_type_id string FK
        item_number string
        product_name_zh string
        product_name_id string
        product_code string
        service_type_name_zh string
        service_type_name_id string
        quantity string
        unit string
        unit_price string
        discount_amount string
        ...
    }

    order_stages {
        id string PK
        order_id string FK
        assigned_to_user_id string FK
        created_by string FK
        updated_by string FK
        stage_name string
        stage_code string
        stage_order string
        status string
        started_at string
        completed_at string
        progress_percent string
        notes string
        created_at string
        updated_at string
    }

    order_statuses {
        id string PK
        code string
        name string
        description string
        display_order string
        is_active string
        created_at string
        updated_at string
    }

    orders {
        id string PK
        customer_id string FK
        product_id string FK
        sales_user_id string FK
        status_id string FK
        created_by string FK
        updated_by string FK
        service_record_id string FK
        workflow_instance_id string FK
        order_number string
        title string
        product_name string
        sales_username string
        quantity string
        unit_price string
        total_amount string
        currency_code string
        discount_amount string
        final_amount string
        ...
    }

    organization_domains {
        id string PK
        organization_id string FK
        domain_id string FK
        code string
        name_zh string
        name_id string
        description_zh string
        description_id string
        display_order string
        is_active string
        created_at string
        updated_at string
        is_primary string
        ...
    }

    organization_employees {
        id string PK
        user_id string FK
        organization_id string FK
        created_by string FK
        updated_by string FK
        first_name string
        last_name string
        full_name string
        email string
        phone string
        position string
        department string
        employee_number string
        is_primary string
        is_manager string
        ...
    }

    organizations {
        id string PK
        parent_id string FK
        verified_by string FK
        name string
        code string
        external_id string
        organization_type string
        email string
        phone string
        website string
        logo_url string
        description string
        street string
        ...
    }

    payment_stages {
        id string PK
        order_id string FK
        service_record_id string FK
        created_by string FK
        updated_by string FK
        order_number string
        stage_number string
        stage_name string
        stage_description string
        amount string
        paid_amount string
        remaining_amount string
        currency_code string
        payment_condition string
        payment_trigger string
        ...
    }

    payments {
        id string PK
        order_id string FK
        confirmed_by string FK
        created_by string FK
        payment_stage_id string FK
        payment_type string
        amount string
        currency_code string
        payment_method string
        payment_date string
        received_at string
        transaction_id string
        bank_account string
        payer_name string
        payer_account string
        ...
    }

    permissions {
        id string PK
        role_id string FK
        permission_id string FK
        parent_id string FK
        menu_id string FK
        code string
        name_zh string
        name_id string
        description_zh string
        description_id string
        resource_type string
        action string
        display_order string
        is_active string
        created_at string
    }

    product_categories {
        id string PK
        code string
        name string
        created_at string
        updated_at string
    }

    products {
        id string PK
        vendor_id string FK
        category_id string FK
        id_external string
        owner_id_external string
        owner_name string
        created_by_external string
        created_by_name string
        updated_by_external string
        updated_by_name string
        created_at_src string
        updated_at_src string
        last_action_at_src string
        ...
    }

    role_permissions {
        role_id string FK
        permission_id string FK
        created_at string
    }

    roles {
        id string PK
        parent_id string FK
        verified_by string FK
        organization_id string FK
        user_id string FK
        role_id string FK
        created_by string FK
        updated_by string FK
        vendor_id string FK
        category_id string FK
        parent_customer_id string FK
        source_id string FK
        channel_id string FK
        owner_user_id string FK
        agent_user_id string FK
        agent_id string FK
        customer_id string FK
        product_id string FK
        sales_user_id string FK
        status_id string FK
        order_id string FK
        assigned_to_user_id string FK
        assigned_by_user_id string FK
        organization_employee_id string FK
        vendor_employee_id string FK
        order_stage_id string FK
        uploaded_by string FK
        confirmed_by string FK
        code string
        name string
        description string
        created_at string
        updated_at string
    }

    service_records {
        id string PK
        customer_id string FK
        service_type_id string FK
        product_id string FK
        contact_id string FK
        sales_user_id string FK
        referral_customer_id string FK
        created_by string FK
        updated_by string FK
        id_external string
        owner_id_external string
        owner_name string
        created_by_external string
        created_by_name string
        updated_by_external string
        updated_by_name string
        created_at_src string
        updated_at_src string
        last_action_at_src string
        ...
    }

    user_roles {
        user_id string FK
        role_id string FK
    }

    users {
        id string PK
        username string
        email string
        phone string
        display_name string
        password_hash string
        avatar_url string
        bio string
        gender string
        address string
        contact_phone string
        ...
    }

    vendor_extensions {
        organization_id string PK
        organization_id string FK
        account_group string
        category_name string
        created_at string
        updated_at string
    }

    visa_records {
        id string PK
        customer_id string FK
        id_external string
        owner_id_external string
        owner_name string
        created_by_external string
        created_by_name string
        updated_by_external string
        updated_by_name string
        created_at_src string
        updated_at_src string
        last_action_at_src string
        ...
    }

    workflow_definitions {
        id string PK
        created_by string FK
        updated_by string FK
        workflow_definition_id string FK
        started_by string FK
        workflow_instance_id string FK
        assigned_to_user_id string FK
        assigned_to_role_id string FK
        completed_by string FK
        triggered_by string FK
        order_id string FK
        product_id string FK
        service_type_id string FK
        order_stage_id string FK
        replied_to_comment_id string FK
        order_item_id string FK
        verified_by string FK
        uploaded_by string FK
        name_zh string
        name_id string
        code string
        description_zh string
        description_id string
        workflow_type string
        definition_json string
        version string
        is_active string
        created_at string
    }

    workflow_instances {
        id string PK
        workflow_definition_id string FK
        started_by string FK
        business_type string
        business_id string
        current_stage string
        status string
        started_at string
        completed_at string
        variables string
        created_at string
        updated_at string
    }

    workflow_tasks {
        id string PK
        workflow_instance_id string FK
        assigned_to_user_id string FK
        assigned_to_role_id string FK
        completed_by string FK
        task_name_zh string
        task_name_id string
        task_code string
        task_type string
        status string
        due_date string
        completed_at string
        variables string
        created_at string
        updated_at string
    }

    workflow_transitions {
        id string PK
        workflow_instance_id string FK
        triggered_by string FK
        from_stage string
        to_stage string
        transition_condition string
        triggered_at string
        notes string
        created_at string
    }

    %% Relationships
    organizations ||--o{ organizations : "parent_id"
    organizations ||--o{ users : "verified_by"
    vendor_extensions ||--o{ organizations : "organization_id"
    agent_extensions ||--o{ organizations : "organization_id"
    user_roles ||--o{ users : "user_id"
    user_roles ||--o{ roles : "role_id"
    organization_employees ||--o{ users : "user_id"
    organization_employees ||--o{ organizations : "organization_id"
    organization_employees ||--o{ users : "created_by"
    organization_employees ||--o{ users : "updated_by"
    products ||--o{ organizations : "vendor_id"
    products ||--o{ product_categories : "category_id"
    customers ||--o{ customers : "parent_customer_id"
    customers ||--o{ customer_sources : "source_id"
    customers ||--o{ customer_channels : "channel_id"
    customers ||--o{ users : "owner_user_id"
    customers ||--o{ users : "agent_user_id"
    customers ||--o{ organizations : "agent_id"
    contacts ||--o{ customers : "customer_id"
    contacts ||--o{ users : "created_by"
    contacts ||--o{ users : "updated_by"
    visa_records ||--o{ customers : "customer_id"
    orders ||--o{ customers : "customer_id"
    orders ||--o{ products : "product_id"
    orders ||--o{ users : "sales_user_id"
    orders ||--o{ order_statuses : "status_id"
    orders ||--o{ users : "created_by"
    orders ||--o{ users : "updated_by"
    order_assignments ||--o{ orders : "order_id"
    order_assignments ||--o{ users : "assigned_to_user_id"
    order_assignments ||--o{ users : "assigned_by_user_id"
    order_assignments ||--o{ organizations : "vendor_id"
    order_assignments ||--o{ organization_employees : "organization_employee_id"
    order_assignments ||--o{ organization_employees : "vendor_employee_id"
    order_stages ||--o{ orders : "order_id"
    order_stages ||--o{ users : "assigned_to_user_id"
    order_stages ||--o{ users : "created_by"
    order_stages ||--o{ users : "updated_by"
    deliverables ||--o{ orders : "order_id"
    deliverables ||--o{ order_stages : "order_stage_id"
    deliverables ||--o{ users : "verified_by"
    deliverables ||--o{ users : "uploaded_by"
    payments ||--o{ orders : "order_id"
    payments ||--o{ users : "confirmed_by"
    payments ||--o{ users : "created_by"
    roles ||--o{ organizations : "parent_id"
    roles ||--o{ users : "verified_by"
    roles ||--o{ organizations : "organization_id"
    roles ||--o{ users : "user_id"
    roles ||--o{ roles : "role_id"
    roles ||--o{ users : "created_by"
    roles ||--o{ users : "updated_by"
    roles ||--o{ organizations : "vendor_id"
    roles ||--o{ product_categories : "category_id"
    roles ||--o{ customers : "parent_customer_id"
    roles ||--o{ customer_sources : "source_id"
    roles ||--o{ customer_channels : "channel_id"
    roles ||--o{ users : "owner_user_id"
    roles ||--o{ users : "agent_user_id"
    roles ||--o{ organizations : "agent_id"
    roles ||--o{ customers : "customer_id"
    roles ||--o{ products : "product_id"
    roles ||--o{ users : "sales_user_id"
    roles ||--o{ order_statuses : "status_id"
    roles ||--o{ orders : "order_id"
    roles ||--o{ users : "assigned_to_user_id"
    roles ||--o{ users : "assigned_by_user_id"
    roles ||--o{ organization_employees : "organization_employee_id"
    roles ||--o{ organization_employees : "vendor_employee_id"
    roles ||--o{ order_stages : "order_stage_id"
    roles ||--o{ users : "uploaded_by"
    roles ||--o{ users : "confirmed_by"
    orders ||--o{ service_records : "service_record_id"
    orders ||--o{ workflow_instances : "workflow_instance_id"
    workflow_definitions ||--o{ users : "created_by"
    workflow_definitions ||--o{ users : "updated_by"
    workflow_instances ||--o{ workflow_definitions : "workflow_definition_id"
    workflow_instances ||--o{ users : "started_by"
    workflow_tasks ||--o{ workflow_instances : "workflow_instance_id"
    workflow_tasks ||--o{ users : "assigned_to_user_id"
    workflow_tasks ||--o{ roles : "assigned_to_role_id"
    workflow_tasks ||--o{ users : "completed_by"
    workflow_transitions ||--o{ workflow_instances : "workflow_instance_id"
    workflow_transitions ||--o{ users : "triggered_by"
    order_items ||--o{ orders : "order_id"
    order_items ||--o{ products : "product_id"
    order_comments ||--o{ orders : "order_id"
    order_comments ||--o{ order_stages : "order_stage_id"
    order_comments ||--o{ order_comments : "replied_to_comment_id"
    order_comments ||--o{ users : "created_by"
    order_files ||--o{ orders : "order_id"
    order_files ||--o{ order_items : "order_item_id"
    order_files ||--o{ order_stages : "order_stage_id"
    order_files ||--o{ users : "verified_by"
    order_files ||--o{ users : "uploaded_by"
    workflow_definitions ||--o{ workflow_definitions : "workflow_definition_id"
    workflow_definitions ||--o{ users : "started_by"
    workflow_definitions ||--o{ workflow_instances : "workflow_instance_id"
    workflow_definitions ||--o{ users : "assigned_to_user_id"
    workflow_definitions ||--o{ roles : "assigned_to_role_id"
    workflow_definitions ||--o{ users : "completed_by"
    workflow_definitions ||--o{ users : "triggered_by"
    workflow_definitions ||--o{ orders : "order_id"
    workflow_definitions ||--o{ products : "product_id"
    workflow_definitions ||--o{ order_stages : "order_stage_id"
    workflow_definitions ||--o{ order_comments : "replied_to_comment_id"
    workflow_definitions ||--o{ order_items : "order_item_id"
    workflow_definitions ||--o{ users : "verified_by"
    workflow_definitions ||--o{ users : "uploaded_by"
    organization_domains ||--o{ organizations : "organization_id"
    organization_domains ||--o{ organization_domains : "domain_id"
    role_permissions ||--o{ roles : "role_id"
    role_permissions ||--o{ permissions : "permission_id"
    menus ||--o{ menus : "parent_id"
    menu_permissions ||--o{ menus : "menu_id"
    menu_permissions ||--o{ permissions : "permission_id"
    permissions ||--o{ roles : "role_id"
    permissions ||--o{ permissions : "permission_id"
    permissions ||--o{ menus : "parent_id"
    permissions ||--o{ menus : "menu_id"
    service_records ||--o{ customers : "customer_id"
    service_records ||--o{ products : "product_id"
    service_records ||--o{ contacts : "contact_id"
    service_records ||--o{ users : "sales_user_id"
    service_records ||--o{ customers : "referral_customer_id"
    service_records ||--o{ users : "created_by"
    service_records ||--o{ users : "updated_by"
    payments ||--o{ payment_stages : "payment_stage_id"
    customer_documents ||--o{ customers : "customer_id"
    customer_documents ||--o{ users : "verified_by"
    customer_documents ||--o{ users : "created_by"
    customer_documents ||--o{ users : "updated_by"
    payment_stages ||--o{ orders : "order_id"
    payment_stages ||--o{ service_records : "service_record_id"
    payment_stages ||--o{ users : "created_by"
    payment_stages ||--o{ users : "updated_by"
    customer_documents ||--o{ orders : "order_id"
    customer_documents ||--o{ service_records : "service_record_id"